### ISSUE TITLE
Failures with latest update

### ISSUE THREAD

**Issue by vitobotta** [juliangruber/find-pull-request-action#35]
Hi! Thanks for this useful project. The action started to fail for me a few minutes ago with the error `GitHub is not a constructor`. I see you have made a release minutes ago. Do I need to change anything? I am using it according to the current README. Thanks!

**Comment by juliangruber** [comment]
taking a look this moment

**Comment by juliangruber** [comment]
fixed https://github.com/juliangruber/find-pull-request-action/releases/tag/v1.7.2

**Comment by vitobotta** [comment]
Wow that was fast! I can confirm that it's working again now. Huge thanks!
